version: '3.7'

services:
  rabbit:
    image: rabbitmq:3
  inference_server_0:
    image: inference_server
    build:
      context: .
    command: ["python", "inference_server.py", "model_0"]
  metrics_server_0:
    image: metrics_server
    build:
      context: .
    command: ["python", "metrics_server.py", "model_0"]
